language: node_js
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install --ignore-scripts
script:
  - npm run lint
  - npm run build
  - npm run test
node_js:
  - "stable"
  - "4"
  - "0.12"
